var myArray = [1, 2, 3];
var theSameArray = new Array(1, 2, 3);

console.log(myArray[1]); // prints out 2

var myArray = []
myArray[3] = "hello"
console.log(myArray); // prints the following
[undefined, undefined, undefined, "hello"]

var myArray = ["string", 10, {}]

//Exercise
// You must define an array with the following three variables:
// A string which has the value of "What is the meaning of life?"
// A number which has a value of 42
// A boolean which has a value of true


var myArray = ["What is the meaning of life?", 42, true];
console.log(myArray[0]);
console.log(myArray[1]);
console.log(myArray[2]);