var myNumber = 3; // a number
var myString = "Hello, World!" // a string
var myBoolean = true; // a boolean

var myArray = []; // an array
var myObject = {}; // an object

var newVariable;
console.log(newVariable); //prints undefined

var emptyVariable = null;
console.log(emptyVariable);

// Exercise
// You must define the following variables:
// A number called myNumber which contains the number 4;
// A string called myString which contains the sentence Variables are great.;
// A boolean called myBoolean which contains the value false;


var myNumber = 4;
var myString = "Variables are great.";
var myBoolean = false;
console.log("myNumber is equal to " + myNumber);
console.log("myString is equal to " + myString);
console.log("myBoolean is equal to " + myBoolean);